### ISSUE TITLE
[Feat] Add effect in project page & add button in navbar to go on landing page 

### ISSUE THREAD

**Issue by MOHIT-IITP** [mrpankajpandey/ai-course-generator#10]
### Description

1: add effect in project page (like hover , etc) for more interactive ui
2: add button in navbar to go on lading page 

### Screenshots

![Screenshot 2024-10-11 at 12 54 51 PM](https://github.com/user-attachments/assets/c0c02d0a-d831-446f-bea3-f3de9a40235f)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mrpankajpandey/ai-course-generator/blob/main/CONTRIBUTING.md)
- [ ] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by pa1narendra** [comment]
@MOHIT-IITP  did you completed the local setup of this project ? I have some doubts.

**Comment by MOHIT-IITP** [comment]
@pa1narendra  it is giving error 
![Screenshot 2024-10-11 at 7 11 03 PM](https://github.com/user-attachments/assets/0ff23bab-f711-4285-af4a-d40448a66659)

**Comment by mrpankajpandey** [comment]
Setup your clerk auth, locally put your all apikey in .env

**Comment by pa1narendra** [comment]
@mrpankajpandey I'll be doing the documentation for that , no other contributor should face this.

@MOHIT-IITP yeah , initially I got that error that's why I asked you , after a lot of self work I finally made it to work, (not fully) but it is running and giving the UI as in the site that it is deployed.

**Comment by MOHIT-IITP** [comment]
@mrpankajpandey  i have only clerk api key , no gemini key , firebase etc
