### ISSUE TITLE
Misaligned Social Media Icons in Footer

### ISSUE THREAD

**Issue by sambhavbohra** [mrpankajpandey/ai-course-generator#3]
Misaligned Social Media Icons in Footer

### Problem:
The social media icons in the footer are not aligned properly and are clustered in the bottom-right corner, which disrupts the overall design.

### Proposed Solution:
1. Use Flexbox or CSS Grid to align the social media icons evenly with appropriate spacing.
2. Ensure that the icons are vertically aligned with the text links in the footer for a cleaner layout.

### Steps to Fix:
- Apply Flexbox or CSS Grid to the footer container.
- Adjust the spacing between the icons using margin or padding.
- Ensure vertical alignment with other footer elements (text links).

##ScreenShot
![UPDATE](https://github.com/user-attachments/assets/29a16904-7a71-41f3-82a8-f591142a07dd)

**Comment by sambhavbohra** [comment]
@mrpankajpandey Please Assign me this issue !

**Comment by sambhavbohra** [comment]
@mrpankajpandey Can you please send me link of social media or should I just add login page of the particular social media platform ??

**Comment by mrpankajpandey** [comment]
All social media link in this project check it out,
