### ISSUE TITLE
Improve Footer Design for Enhanced Visual Appeal

### ISSUE THREAD

**Issue by mahenoorsalat** [mrpankajpandey/ai-course-generator#9]
### Description

**Description**  

The current footer design lacks the visual impact I envision. I would like to enhance the footer to make it more impressive and professional, incorporating improved typography, color schemes, and layout. This should align with the overall aesthetic of the website while ensuring accessibility and responsiveness.

**Alternative Solutions or Features Considered**  

- Considered using a minimalistic design with subtle animations.

- Thought of adding social media icons with hover effects for interactivity.

- Possible inclusion of a newsletter sign-up form for user engagement.

Please assign me this issue .. 

Looking forward to your response .. Thank you :)

Ping @mrpankajpandey 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mrpankajpandey/ai-course-generator/blob/main/CONTRIBUTING.md)
- [ ] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mrpankajpandey** [comment]
Sure, Share your work Screehshot
